In [1]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [4]:
a = np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
print(a)

[1 2 3 4]


In [7]:
a.dtype

dtype('int32')

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
a.itemsize


4

In [11]:
a.tolist()

[1, 2, 3, 4]

In [12]:
c=np.array([1,2,3])

In [13]:
d=np.array([1,2,3])

In [14]:
c is d

False

In [17]:
e = np.asarray(c)

In [18]:
c is e

True

In [19]:
f = c.copy()


In [20]:
c is f

False

In [21]:
import pandas as pd


In [23]:
s = pd.Series([1,2,3,4], index=list('abcd'))

In [24]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [25]:
s.values


array([1, 2, 3, 4], dtype=int64)

In [26]:
s.index


Index(['a', 'b', 'c', 'd'], dtype='object')

In [27]:
s.ndim

1

In [28]:
s.shape

(4,)

In [29]:
s.size

4

In [30]:
s['a']

1

In [31]:
s['d']

4

In [32]:
s['a':'c']

a    1
b    2
c    3
dtype: int64

In [33]:
s[:]

a    1
b    2
c    3
d    4
dtype: int64

In [34]:
s[:-1]

a    1
b    2
c    3
dtype: int64

In [37]:
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]], index=list('ab'), columns=list('abcd'))

In [38]:
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8