In [1]:
import numpy as np

In [2]:
my_list = [0,1,2,3,4,5,6,7,8,9,10]
nparr = np.array(my_list)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
nparr=np.arange(0,11)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
nparr_added = nparr + nparr
print(nparr_added)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [5]:
nparr_sub= nparr-nparr
print(nparr_sub)

[0 0 0 0 0 0 0 0 0 0 0]


In [6]:
nparr_mult = nparr * nparr
print(nparr_mult)

[  0   1   4   9  16  25  36  49  64  81 100]


In [7]:
nparr_div = nparr / nparr
print(nparr_div)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-7-ac3be0a7341d>:1: RuntimeWarning: invalid value encountered in true_divide
  nparr_div = nparr / nparr


In [8]:
nparr_esc = nparr * 10
print(nparr_esc)

[  0  10  20  30  40  50  60  70  80  90 100]


In [9]:
nparr_one_div = 1/nparr
print(nparr_one_div)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


<ipython-input-9-3d17f1fc195b>:1: RuntimeWarning: divide by zero encountered in true_divide
  nparr_one_div = 1/nparr


In [10]:
nparr_max = np.max(nparr)
print(nparr_max)

10


In [11]:
nparr_min = np.min(nparr)
print(nparr_min)

0


In [12]:
arr_10to50 = np.arange(10,51)
print(arr_10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [13]:
arr_10to50_even = np.arange(10,51,2)
print(arr_10to50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [14]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.random.rand(1)

array([0.60974752])

In [16]:
np.random.randn(25)

array([-1.11824836,  1.29993604, -0.18864261,  1.05526019, -0.04209382,
       -0.23293784,  1.03056853, -0.53382386, -0.57417162, -1.11431893,
       -1.11171281,  0.20444394,  0.65373682, -1.2766574 , -0.19996317,
        0.12692515, -1.69825393, -1.66606688, -0.23275388,  0.25016232,
       -0.27660371,  1.62882836,  0.5994176 , -1.83515124, -0.40210318])

In [17]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [18]:
arr_2_d = np.arange(1,26).reshape(5,5)
print(arr_2_d)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
arr_2_d[3,4]

20

In [20]:
arr_2_d[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
arr_2_d[4,:]

array([21, 22, 23, 24, 25])

In [22]:
np.sum(arr_2_d)

325

In [23]:
arr_2_d.sum()

325

In [24]:
np.std(arr_2_d)

7.211102550927978

In [25]:
arr_2_d.std()

7.211102550927978

![nn](10.png)

In [26]:
arr_2_d.sum(axis=0)
# axis=0 -> row -> so the result is placed in a row
# (then it is a columns' sum)
# axis=1 -> columns -> so the result is placed in a column 
# (then it is a row's sum:)

array([55, 60, 65, 70, 75])

In [27]:
arr_2_d.sum(axis=1)

array([ 15,  40,  65,  90, 115])